project:
  type: website
  output-dir: docs
  
website:
  title: "AbigailAxness"
  navbar:
    left:
      - href: index.qmd
      - href: about.qmd
      - href: Education.qmd
      - href: Experience.qmd
      - href: Awards and Honors.qmd
       
    #  - about.qmd
    #  - Education.qmd
    #  - Experience.qmd
    #  - Awards and Honors.qmd


format:
  html:
    theme: 
      light: solar
      dark: lux
    css: styles.css

editor: visual

