---
title: "Awards and Honors"
---

\- Quaternary Geology and Geomorphology (QG&G) Division of the Geological Society of America’s Donald R. Coates Award for 2023 for my research proposal: Uncovering the Drivers of Mountain Relief in the Granodiorite and Volcaniclastic Bedrock of Puerto Rico.

\-National Science Foundation's Bridge to the Doctorate Fellowship for Master's Completion at Boise State University.

\- Diversity Participation Award at the IALE-NA Conference.

\- NSF Grant: EAGER Collaborative Research Board Member.

\- Pacific Northwest LSAMP Conference Panelist.

\- New Mexico Homegrown Scientist's Panelist.

\- Alliance for Minority Participation Recipient.

\- Geological Society of America's J. David Lowell Field Camp Scholarship.

\- Excellence in Undergraduate Student Research Awards, UNM.

\- Stuart A. Northrop Award, UNM.

\- Leonard Research Fellowship.

\- Leadership & Involvement Award, UNM.

\- AWG Sand Student Research Presentation Travel Award.

\- STEAM Honorary Participant, Dream Builders Workshop.
